### PR TITLE
EventEmitter bug fixed & add readable-stream for devDependencies

### PR DESCRIPTION
**Pull request by helloyou2012**

### CODE REVIEW

**Comment by iarna** [comment]
That event emitter change doesn't look right to me, see the example from the docs:

https://nodejs.org/api/events.html

```
const EventEmitter = require('events');
const util = require('util');

function MyEmitter() {
  EventEmitter.call(this);
}
util.inherits(MyEmitter, EventEmitter);
```

The readable stream thing is a good catch though and I'll take that part.

**Comment by iarna** [comment]
Ah, the EventEmitter thing is `0.10`, ok, then I'll take that too =D

**Comment by helloyou2012** [comment]
Yes, for `0.10` hack, see: https://github.com/nodejs/node/blob/master/lib/events.js#L12

**Comment by iarna** [comment]
Thank you for these, I've landed them as:

19a5030 &  42689f0

**Pull request closed without merging**
