### PR TITLE
fix: move to template-oss

### PR DESCRIPTION
**Pull request by wraithgar**
BREAKING CHANGE: this drops support for node10 and non-LTS node 12 and
14.

### CODE REVIEW

**Comment by jimmywarting** [comment]
Take this breaking opportunity to switch to ESM-only 🙃

**Comment by lukekarrys** [comment]
@wraithgar I updated to the latest `@npmcli/template-oss` with the `.gitignore` check and got this nice error message 😄 

```
Some problems were detected:

The following files are tracked by git but matching a pattern in .gitignore:
  .travis.yml

To correct them:
Move files to not match one of these patterns:
  /*
  !/.eslintrc*
  !/.github
  !**/.gitignore
  !/package.json
  !/package-lock.json
  !/docs
  !/bin
  !/lib
  !/map.js
  !/tap-snapshots
  !/test
  !/scripts
  !/README*
  !/LICENSE*
  !/SECURITY*
  !/CHANGELOG*
```

So I pushed a commit remove `.travis.yml` and fixed the path to the demo gif.

**Review by lukekarrys — APPROVED** [review]

**Comment by stof** [comment]
demo.js should go in `docs/` rather than `lib/`

**Comment by mattolson** [comment]
Thanks for the upgrades!

**Pull request merged**
