### PR TITLE
Set Unicode startgroup and endgroup to empty string by default

### PR DESCRIPTION
**Pull request by dbkaplun**

### CODE REVIEW

**Comment by dbkaplun** [comment]
What do you think about this @iarna? I think it looks much better and simpler without the start/end groups.

**Comment by iarna** [comment]
Obviously I disagree since I put them there. ;)

Let's hold of on aesthetics here for the redesigned gauge.

**Comment by dbkaplun** [comment]
Just saw that screenshot from #5.. they look great! But unfortunately it doesn't work with any of my fonts:
screenshot

**Comment by iarna** [comment]
@dbkaplun That screenshot you posted looks entirely normal…

**Comment by dbkaplun** [comment]
I think the screenshot from #5 was removed.. I remember it had neat fully-filled half-block end caps, it looked kinda like a battery. Removing the end caps entirely like in this PR also makes gauge look more uniform than the screenshot.

**Comment by iarna** [comment]
Hey, I'm closing this in favor of https://github.com/iarna/gauge/issues/36 – I would love feedback and suggestions on how things look.

**Pull request closed without merging**
